apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: faces
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/enrique/STORAGE/faces"   # Ruta en tu host Ubuntu
